"""Regenerate web/charset-data.js from the canonical charset table.

    python3 web/gen-charset.py

Reads tama4u/charset*.json (built by `python3 -m tama4u charset <pack>`)
through charset.canonical_bytes(), which merges the four per-model tables
and repairs the entries each pack got wrong.  The result is committed
because the browser build needs it to work at all.
"""
import json
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))
from tama4u import charset  # noqa: E402

OUT = os.path.join(os.path.dirname(__file__), 'charset-data.js')
HEAD = ('// Generated by web/gen-charset.py from tama4u/charset*.json.\n'
        '// Internal text codes -> characters, per model.  4U stores each\n'
        '// code as 0x04xx; the other three use the bare byte.  All four\n'
        '// share one table -- see charset.canonical_bytes().\n')


def main():
    base = charset.canonical_bytes()
    tables = {m: {str(c + (0x0400 if m == '4U' else 0)): v
                  for c, v in sorted(base.items())}
              for m in charset.MODELS}
    body = json.dumps(tables, ensure_ascii=True, separators=(',', ':'))
    with open(OUT, 'w') as fh:
        fh.write(HEAD + 'export const CHARSET = ' + body + ';\n')
    print(f'{OUT}  {len(base)} chars x {len(tables)} models')


if __name__ == '__main__':
    main()
